server:
  port: 8082

spring:
  task:
    scheduling:
      pool:
        size: 1

odpt:
  api:
    base-url: https://api.odpt.org/api/v4
    consumer-key: ${ODPT_API_KEY}

admin:
  token: ${ADMIN_TOKEN:}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: when_authorized
  metrics:
    tags:
      application: tokyo-last-train
